(define (fast-*-iter a b)
  (iter a b 0))
(define (iter a b s)
  (cond ((= b 0) s)
        ((even? b) (iter (double a) (halve b) s))
        (else (iter a (- b 1) (+ a s)))))
(define (double n)
  (+ n n))
(define (halve n)
  (/ n 2))